### ISSUE TITLE
Firefox Home not working

### ISSUE THREAD

**Issue by gokaybalci** [AnubisZ9/PixelFox#1]
I am using Mozila Firefox 74.0 (64-bit).

After I followed instructions one by one, I got everything working except that default page is blank. If I set my homepage custom url and give the file location, it works flawlessly. But then, url bar says "file:/// etc." so it looks ugly.

Did an update brake the whole thing? What am I doing wrong?

**Comment by 3r3bu5x9** [comment]
> I am using Mozila Firefox 74.0 (64-bit).
> 
> After I followed instructions one by one, I got everything working except that default page is blank. If I set my homepage custom url and give the file location, it works flawlessly. But then, url bar says "file:/// etc." so it looks ugly.
> 
> Did an update brake the whole thing? What am I doing wrong?

What do u mean by default page? The New Tab page?
There's instructions for changing the New tab page to the custom page. If u set it correctly, the ugly file path in the url bar should also disappear.

**Comment by gokaybalci** [comment]
> What do u mean by default page?

I mean, I should select Firefox Home (default) as homepage in preferences, right?

> There's instructions for changing the New tab page to the custom page. If u set it correctly, the ugly file path in the url bar should also disappear.

I did. I even changed the "var clearlocationbar" value to yes manually. I didn't help. I don't know what's the problem here, really.

**Comment by 3r3bu5x9** [comment]
> I mean, I should select Firefox Home (default) as homepage in preferences, right?

No, you are supposed to select custom URLs and then enter the path of the index.html there.

**Comment by gokaybalci** [comment]
Yeah, I tried that too. That is how I am using now. But still, url bar is not clear. I have to manually clear every time I have to type.

**Comment by 3r3bu5x9** [comment]
what happens when u press Ctrl+t? do u get the custom page? or the firefox new tab page?

**Comment by gokaybalci** [comment]
I get a blank page even though it is set to Firefox Home (default).

**Comment by 3r3bu5x9** [comment]
so ur custom new tab page is not working.You cannot set it from preferences. This is from the instructions:

> To enable the newtab startpage functionality open userChrome.js and then change const mypage = "file:///home/debasis/.mozilla/firefox/sawjo289.default-esr/startpage/index.html"; Put the path of your index.html in the quotation.

 All 3 userChrome files must be in the chrome dir. If this works, the ugly address in the home page should also disappear.

**Comment by gokaybalci** [comment]
I got 3 userChrome files (userChrome.css, userChrome.js and userChrome.xml) in chrome dir and I've edited the "const mypage" to my index file which is located in startpage folder in Firefox profile dir. Still not working though. Anyways, the problem is personal I guess. I will try to solve it myself. Thanks for the help, though. Have a nice evening.
