### ISSUE TITLE
Inconsistent Colors

### ISSUE THREAD

**Issue by ZN0N15** [AnubisZ9/PixelFox#2]
Hi, first off, I love this Firefox design scheme you made. 
But I need some assistance in figuring out this issue about the colors from the theme. 

![screenshot2021-01-08-15:09:21](https://user-images.githubusercontent.com/57549197/103985244-8bbfaf80-51c3-11eb-83aa-a84408a928d0.png)

As you can see, below where the tabs are, there is a tiny black strip, which I assume is the padding/spacing of the tab area. 
Then, on the startpage, there's this portion from the top and bottom of the page that has a much darker gray color that I can't seen to figure out why it's like that. I tried to fix it by messing with the style.css file to change the color of that particular section of the page but with no avail.

The black strip below the tab line and the top/bottom portion of the startpage have inconsistent colors that I can't seem to fix. 
I have tried using this with Waterfox, but I still get the same result.

This screenshot has default settings btw, nothing changed in the configs.

**Comment by 3r3bu5x9** [comment]
I made some changes in the style.css file. Check if the issue persists.

**Comment by ZN0N15** [comment]
Thanks! it works! 

The only problem I can't seem to figure out is that strip below the tabs. 
I just found out, that strip isn't just "Black", it's dependent on what Firefox UI theme I set. For example; If I set my Firefox theme to 'Light' that strip becomes white, If I set it to 'Dark' it becomes black, If I set it to 'Firefox Alpenglow' I get the colorful purple and yellow color strip.

Any ideas on how to fix it?
Or is this normal and I'm not actually using the correct Firefox Theme? If so, what theme should I use to blend in the greyish color with the startpage and the tabs?

**Comment by 3r3bu5x9** [comment]
Check line 39 and 41 in the userChrome.css file in the chrome folder. Change margin-left to 0px and margin-bottom to 0px. Edit: I updated the code.

**Comment by ZN0N15** [comment]
It Works!
Thanks again!

**Comment by ZN0N15** [comment]
Also just to let you know I managed to fix that strip gap from margin spacing by adding a few lines to userChrome.css

`.toolbar-items {
  background-color: #292D31 !important;
}`

changes the toolbar background color to match everything else with the tabs without removing the margins.
